on:
  push:
    branches:
    - main

jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup - gcloud / gsutil
        uses: google-github-actions/setup-gcloud@main
        with:
          service_account_key: ${{ secrets.GCS_SA_KEY }}
          project_id: ${{ secrets.GCS_PROJECT }}
          export_default_credentials: true

      - name: Deploy
        run: |-
          git clone https://github.com/tigerjz32/keysmashfun/
          rm -rf keysmashfun/.git
          gsutil -m rsync -R keysmashfun gs://${{ secrets.GCS_BUCKET }}